---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rpc-app-demo
  namespace: monitoring
  labels:
    team: devops-bootcamp
spec:
  endpoints:
  - honorLabels: true
    port: web
  selector:
    matchLabels:
      app: rpc-app
